config/routes.rb
Rails.application.routes.draw do
  resources :js_sripts
  root to: 'js_sripts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/js_sript.rb
class JsSript < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_script


    def set_script
        @script = JsSript.first.try(:chatscript)
    end
end

app/controllers/js_sripts_controller.rb
class JsSriptsController < ApplicationController
  before_action :set_js_sript, only: %i[ show edit update destroy ]

  # GET /js_sripts or /js_sripts.json
  def index
    @js_sripts = JsSript.all
  end

  # GET /js_sripts/1 or /js_sripts/1.json
  def show
  end

  # GET /js_sripts/new
  def new
    @js_sript = JsSript.new
  end

  # GET /js_sripts/1/edit
  def edit
  end

  # POST /js_sripts or /js_sripts.json
  def create
    @js_sript = JsSript.new(js_sript_params)

    respond_to do |format|
      if @js_sript.save
        format.html { redirect_to @js_sript, notice: "Js sript was successfully created." }
        format.json { render :show, status: :created, location: @js_sript }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @js_sript.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /js_sripts/1 or /js_sripts/1.json
  def update
    respond_to do |format|
      if @js_sript.update(js_sript_params)
        format.html { redirect_to @js_sript, notice: "Js sript was successfully updated." }
        format.json { render :show, status: :ok, location: @js_sript }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @js_sript.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /js_sripts/1 or /js_sripts/1.json
  def destroy
    @js_sript.destroy
    respond_to do |format|
      format.html { redirect_to js_sripts_url, notice: "Js sript was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_js_sript
      @js_sript = JsSript.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def js_sript_params
      params.require(:js_sript).permit(:chatscript)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/js_sripts_helper.rb
module JsSriptsHelper
end

app/views/js_sripts/_form.html.erb
<%= form_with(model: js_sript) do |form| %>
  <% if js_sript.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(js_sript.errors.count, "error") %> prohibited this js_sript from being saved:</h2>

      <ul>
        <% js_sript.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :chatscript %>
    <%= form.text_field :chatscript %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/js_sripts/edit.html.erb
<h1>Editing Js Sript</h1>

<%= render 'form', js_sript: @js_sript %>

<%= link_to 'Show', @js_sript %> |
<%= link_to 'Back', js_sripts_path %>

app/views/js_sripts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Js Sripts</h1>

<table>
  <thead>
    <tr>
      <th>Chatscript</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @js_sripts.each do |js_sript| %>
      <tr>
        <td><%= js_sript.chatscript %></td>
        <td><%= link_to 'Show', js_sript %></td>
        <td><%= link_to 'Edit', edit_js_sript_path(js_sript) %></td>
        <td><%= link_to 'Destroy', js_sript, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Js Sript', new_js_sript_path %>

app/views/js_sripts/new.html.erb
<h1>New Js Sript</h1>

<%= render 'form', js_sript: @js_sript %>

<%= link_to 'Back', js_sripts_path %>

app/views/js_sripts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Chatscript:</strong>
  <%= @js_sript.chatscript %>
</p>

<%= link_to 'Edit', edit_js_sript_path(@js_sript) %> |
<%= link_to 'Back', js_sripts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webinbox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= raw @script  %>
  </head>

  <body>
    <%= yield %>
    
  </body>
</html>